# See https://golangci-lint.run/usage/linters/

linters:
  enable-all: true
  disable:
    # Note: deprecated linters
    - gomnd
    - execinquery
    - exportloopref
    # Disable wsl
    - wsl
issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - depguard
        - exhaustruct
        - gci
        - lll
        - wrapcheck
    - path: '(.+)(?:brotli|gzip|reporter|wrapper|validator)\.go'
      linters:
        - wrapcheck
    - path: '(.+)validator\.go'
      linters:
        - err113
    - path: '(.+)(health_test|dbstorage_test)\.go'
      linters:
        - ireturn
    - path: '(.+)(signature|signature_test)\.go'
      linters:
        - canonicalheader
linters-settings:
  varnamelen:
    min-name-length: 2  # Adjust the minimum length as needed
    skip-names:
      - wg
  goimports:
    local-prefixes: github.com/npavlov/go-metrics-service
  gci:
    skip-generated: true
    sections:
      - Standard
      - Default
      - Prefix(github.com/npavlov/go-metrics-service)
    skip-non-go: true
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd