linters:
  enable-all: true
  disable:
    # Note: deprecated linters
    - gomnd
    - execinquery
    - exportloopref
    # Disable naming
    - varnamelen
    # Disable wsl
    - wsl
issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - depguard
        - exhaustruct
        - gci
        - lll
        - wrapcheck
    - path: '(.+)builder\.go'
      linters:
        - exhaustruct
    - path: '(.+)stats\.go'
      linters:
        - exhaustruct
        - prealloc
    - path: '(.+)storage\.go'
      linters:
        - exhaustruct
    - path: '(.+)(?:brotli|gzip|reporter)\.go'
      linters:
        - wrapcheck
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - github.com/npavlov/go-metrics-service/internal/agent/watcher
          - github.com/npavlov/go-metrics-service/internal/agent/stats
          - github.com/npavlov/go-metrics-service/internal/agent/config
          - github.com/npavlov/go-metrics-service/internal/server/config
          - github.com/npavlov/go-metrics-service/internal/utils
          - github.com/npavlov/go-metrics-service/internal/server/templates
          - github.com/npavlov/go-metrics-service/internal/server/storage
          - github.com/npavlov/go-metrics-service/internal/server/middlewares
          - github.com/npavlov/go-metrics-service/internal/server/handlers
          - github.com/npavlov/go-metrics-service/internal/domain
          - github.com/npavlov/go-metrics-service/internal/model
          - github.com/go-chi/chi/v5/middleware'
          - github.com/go-chi/chi/v5
          - github.com/npavlov/go-metrics-service/internal/logger
          - github.com/joho/godotenv
          - encoding/json
          - github.com/pkg/errors
          - strconv
          - github.com/pkg/errors
          - github.com/rs/zerolog
          - github.com/rs/zerolog/log
          - net/http
          - html/template
          - embed
          - github.com/caarlos0/env/v6
          - os
          - syscall
          - runtime/debug
          - fmt
          - github.com/go-chi/chi/v5/middleware
          - flag
          - github.com/go-resty/resty/v2
          - contexts
          - time
          - runtime
          - reflect
          - math/rand
          - sync
          - context
          - io
          - strings
          - compress/gzip
          - bytes
          - github.com/andybalholm/brotli